# Generated by Django 4.1.7 on 2023-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rented", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rented",
            name="book_time",
            field=models.DateField(null=True),
        ),
    ]
