# Generated by Django 4.1.7 on 2023-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rented", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rented",
            name="rented_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
