# Generated by Django 4.1.7 on 2023-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rented", "0003_alter_rented_rented_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rented",
            name="book_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="rented",
            name="devolution_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="rented",
            name="rented_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
