# Generated by Django 4.1.7 on 2023-03-06 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
